# Generated by Django 5.2.1 on 2025-07-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresume',
            name='resume',
            field=models.URLField(),
        ),
    ]
